/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishexportandimportinformationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AdminSignIn extends javax.swing.JFrame {

    /**
     * Creates new form AdminSignIn
     */
    public AdminSignIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAdminUsername = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        lblAdminPassword = new javax.swing.JLabel();
        PassAdminPassword = new javax.swing.JPasswordField();
        btnAdminSignIn = new javax.swing.JButton();
        btnBackAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Log In");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign in.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblAdminUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAdminUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblAdminUsername.setText("Username:");

        txtAdminUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAdminUsername.setForeground(new java.awt.Color(0, 0, 0));
        txtAdminUsername.setToolTipText("");
        txtAdminUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminUsernameActionPerformed(evt);
            }
        });

        lblAdminPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAdminPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblAdminPassword.setText("Password:");

        PassAdminPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PassAdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassAdminPasswordActionPerformed(evt);
            }
        });

        btnAdminSignIn.setBackground(new java.awt.Color(153, 153, 153));
        btnAdminSignIn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdminSignIn.setForeground(new java.awt.Color(0, 0, 51));
        btnAdminSignIn.setText("Sign In");
        btnAdminSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSignInActionPerformed(evt);
            }
        });

        btnBackAdmin.setBackground(new java.awt.Color(153, 153, 153));
        btnBackAdmin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBackAdmin.setForeground(new java.awt.Color(0, 0, 102));
        btnBackAdmin.setText("Back");
        btnBackAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdminSignIn)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnBackAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSignInActionPerformed
  
        try{  
            boolean complete = txtAdminUsername.print();
            
        DBConnection db=new DBConnection();
        String username=txtAdminUsername.getText();
        String password=new String(PassAdminPassword.getPassword());
        String Username = "Fish_Import_And_Export_Information_System";
        String Password="171351996";
        
        if(Username.equals(username) && Password.equals(password)){
            db.dbconnection();
            setVisible(false);
            AdminAfterLogin aal=new AdminAfterLogin();
            aal.setVisible(true);
            db.con.close();
        }
        else{
            close();
            db.con.close();
        }
        db.con.close();

     }
     catch(Exception e){
         JOptionPane.showMessageDialog(null,"Incorrect Username or Password");
     }
        
    }//GEN-LAST:event_btnAdminSignInActionPerformed

        private void close(){
        txtAdminUsername.setText("");
        PassAdminPassword.setText("");
    }
        
    private void btnBackAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAdminActionPerformed
       setVisible(false);
       new FrontPage().setVisible(true);
    }//GEN-LAST:event_btnBackAdminActionPerformed

    private void txtAdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminUsernameActionPerformed
                 
        //txtAdminUsername.setText(username);
    }//GEN-LAST:event_txtAdminUsernameActionPerformed

    private void PassAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassAdminPasswordActionPerformed
        
        //PassAdminPassword.setText(password);
    }//GEN-LAST:event_PassAdminPasswordActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassAdminPassword;
    private javax.swing.JButton btnAdminSignIn;
    private javax.swing.JButton btnBackAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminPassword;
    private javax.swing.JLabel lblAdminUsername;
    private javax.swing.JTextField txtAdminUsername;
    // End of variables declaration//GEN-END:variables
}
