/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishexportandimportinformationsystem;
/**
 *
 * @author user
 */
public class AfterLogin extends javax.swing.JFrame {

    /**
     * Creates new form AfterLogin
     */
    public AfterLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportAfterLogin = new javax.swing.JButton();
        btnManagerSignOut = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnSupplierInfo = new javax.swing.JButton();
        btnExport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setMinimumSize(new java.awt.Dimension(805, 460));
        getContentPane().setLayout(null);

        btnExportAfterLogin.setBackground(new java.awt.Color(255, 153, 102));
        btnExportAfterLogin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnExportAfterLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnExportAfterLogin.setText("Export");
        btnExportAfterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportAfterLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportAfterLogin);
        btnExportAfterLogin.setBounds(230, 240, 210, 60);

        btnManagerSignOut.setBackground(new java.awt.Color(255, 102, 51));
        btnManagerSignOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManagerSignOut.setForeground(new java.awt.Color(0, 0, 0));
        btnManagerSignOut.setText("Sign Out");
        btnManagerSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagerSignOut);
        btnManagerSignOut.setBounds(630, 350, 110, 40);

        btnImport.setBackground(new java.awt.Color(255, 153, 102));
        btnImport.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnImport.setForeground(new java.awt.Color(0, 0, 0));
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        getContentPane().add(btnImport);
        btnImport.setBounds(230, 60, 210, 60);

        btnSupplierInfo.setBackground(new java.awt.Color(255, 153, 102));
        btnSupplierInfo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSupplierInfo.setForeground(new java.awt.Color(0, 0, 0));
        btnSupplierInfo.setText("Supplier Information");
        btnSupplierInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupplierInfo);
        btnSupplierInfo.setBounds(370, 150, 271, 60);

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fishexportandimportinformationsystem/shrimp.jpg"))); // NOI18N
        btnExport.setText("jLabel2");
        btnExport.setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().add(btnExport);
        btnExport.setBounds(0, 0, 790, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        setVisible(false);
        new ImportForm().setVisible(true);
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportAfterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportAfterLoginActionPerformed
        setVisible(false);
        new ExportForm().setVisible(true);
    }//GEN-LAST:event_btnExportAfterLoginActionPerformed

    private void btnManagerSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerSignOutActionPerformed
        setVisible(false);
        new ManagerLogIn().setVisible(true);
    }//GEN-LAST:event_btnManagerSignOutActionPerformed

    private void btnSupplierInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierInfoActionPerformed
        setVisible(false);
        new SupplierInformation().setVisible(true);
    }//GEN-LAST:event_btnSupplierInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExport;
    private javax.swing.JButton btnExportAfterLogin;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnManagerSignOut;
    private javax.swing.JButton btnSupplierInfo;
    // End of variables declaration//GEN-END:variables
}
