/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishexportandimportinformationsystem;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ExportForm extends javax.swing.JFrame {
 
    private String man_id;
    private String m_id;
    /**
     * Creates new form ExportForm
     */
    public ExportForm() {
        initComponents();
            DBConnection db=new DBConnection();
            db.dbconnection();
        this.setLocationRelativeTo(null);
        try{
            String sql="select C_id,C_name,C_country,C_contact_no from Company";
            db.pst=db.con.prepareStatement(sql);
            db.rs=db.pst.executeQuery();
            DefaultTableModel row=(DefaultTableModel) tbtCompanyExport.getModel();
            while(db.rs.next()){
                row.addRow(new Object[]{
                    db.rs.getString("C_id"),db.rs.getString("C_name"),db.rs.getString("C_country"),db.rs.getString("C_contact_no")
                } );
            }
            db.con.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        Company();
    }

     private void Company(){
        try{
            DBConnection db=new DBConnection();
            db.dbconnection();
            String sql="select C_id from Company";
            db.st=db.con.createStatement();
            db.rs=db.st.executeQuery(sql);
            while(db.rs.next()){
                String c_id=db.rs.getString("C_id");
                cmbCompanyIDExportF.addItem(c_id);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error!!!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEProductId = new javax.swing.JLabel();
        lblEProductName = new javax.swing.JLabel();
        lblEPrice = new javax.swing.JLabel();
        lblEQuantity = new javax.swing.JLabel();
        lblECompanyId = new javax.swing.JLabel();
        txtEProductId = new javax.swing.JTextField();
        txtEPrice = new javax.swing.JTextField();
        txtEQuantity = new javax.swing.JTextField();
        lblETax = new javax.swing.JLabel();
        txtETax = new javax.swing.JTextField();
        lblEDate = new javax.swing.JLabel();
        dateExport = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        btnBackExportForm = new javax.swing.JButton();
        btnInsertCompanyInfo = new javax.swing.JButton();
        btnIUpdateCompanyInfo = new javax.swing.JButton();
        btnIDeleteCompanyInfo = new javax.swing.JButton();
        cmboxExportForm = new javax.swing.JComboBox<>();
        lblEManagerId = new javax.swing.JLabel();
        txtEManagerId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtCompanyExport = new javax.swing.JTable();
        cmbCompanyIDExportF = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emport Product Form");

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        lblEProductId.setBackground(new java.awt.Color(0, 102, 204));
        lblEProductId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEProductId.setForeground(new java.awt.Color(255, 255, 255));
        lblEProductId.setText("Product ID:");

        lblEProductName.setBackground(new java.awt.Color(0, 102, 204));
        lblEProductName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblEProductName.setText("Product Name:");

        lblEPrice.setBackground(new java.awt.Color(0, 102, 204));
        lblEPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblEPrice.setText("Price Per Kg:");

        lblEQuantity.setBackground(new java.awt.Color(0, 102, 204));
        lblEQuantity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblEQuantity.setText("Quantity(KG):");

        lblECompanyId.setBackground(new java.awt.Color(0, 102, 204));
        lblECompanyId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblECompanyId.setForeground(new java.awt.Color(255, 255, 255));
        lblECompanyId.setText("Company ID:");

        txtEProductId.setText("P");

        lblETax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblETax.setForeground(new java.awt.Color(255, 255, 255));
        lblETax.setText("Tax (%):");

        lblEDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEDate.setForeground(new java.awt.Color(255, 255, 255));
        lblEDate.setText("Date:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TK");

        btnBackExportForm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBackExportForm.setText("Back");
        btnBackExportForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackExportFormActionPerformed(evt);
            }
        });

        btnInsertCompanyInfo.setBackground(new java.awt.Color(0, 102, 0));
        btnInsertCompanyInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInsertCompanyInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertCompanyInfo.setText("Insert");
        btnInsertCompanyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertCompanyInfoActionPerformed(evt);
            }
        });

        btnIUpdateCompanyInfo.setBackground(new java.awt.Color(0, 0, 51));
        btnIUpdateCompanyInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnIUpdateCompanyInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnIUpdateCompanyInfo.setText("Update");
        btnIUpdateCompanyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIUpdateCompanyInfoActionPerformed(evt);
            }
        });

        btnIDeleteCompanyInfo.setBackground(new java.awt.Color(153, 0, 0));
        btnIDeleteCompanyInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnIDeleteCompanyInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnIDeleteCompanyInfo.setText("Delete");
        btnIDeleteCompanyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDeleteCompanyInfoActionPerformed(evt);
            }
        });

        cmboxExportForm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmboxExportForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chitol", "Common Carp", "Crabs", "Grass Carp", "Ilish", "Katla", "Live Fish", "Lobstar", "Magur", "Pangas", "Prawns", "Rui", "Shing", "Shrimps", "Silver Carp" }));

        lblEManagerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEManagerId.setForeground(new java.awt.Color(255, 255, 255));
        lblEManagerId.setText("Manager ID:");

        txtEManagerId.setText("M");

        tbtCompanyExport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company ID", "Company Name", "Country", "Contact NO."
            }
        ));
        jScrollPane1.setViewportView(tbtCompanyExport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblETax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(lblEProductId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEProductId)
                    .addComponent(txtEQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEPrice)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtETax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateExport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmboxExportForm, 0, 213, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblECompanyId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInsertCompanyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIUpdateCompanyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIDeleteCompanyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbCompanyIDExportF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnBackExportForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateExport, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lblEDate, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lblECompanyId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCompanyIDExportF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEManagerId)
                    .addComponent(lblEManagerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboxExportForm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertCompanyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIUpdateCompanyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIDeleteCompanyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtETax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackExportForm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblETax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackExportFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackExportFormActionPerformed
        setVisible(false);
        new AfterLogin().setVisible(true);
    }//GEN-LAST:event_btnBackExportFormActionPerformed

    private void btnInsertCompanyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertCompanyInfoActionPerformed

        try{
           float price=(float) 0.0;
           float quantity=(float) 0.0;
           float tax=(float) 0.0;
            try{
                 price=Float.parseFloat(txtEPrice.getText());
            }
            catch(NumberFormatException nfe){
                txtEPrice.setText("");
                JOptionPane.showMessageDialog(null,"Insert numeric Value of Price..");
            }
            try{
                quantity=Float.parseFloat(txtEQuantity.getText());
            }
            catch(NumberFormatException nfe){
                txtEQuantity.setText("");
                JOptionPane.showMessageDialog(null,"Insert numeric Value of Quantity..");
            }
            try{
                tax=Float.parseFloat(txtETax.getText());
            }
            catch(NumberFormatException nfe){
                txtETax.setText("");
                JOptionPane.showMessageDialog(null,"Insert numeric Value of Tax..");
            }
            float tax_in_tk=(float) ((price*tax)/100.0);
            float sub_total_price=(tax_in_tk*quantity)+(price*quantity);
            String fish=(String)cmboxExportForm.getSelectedItem();
            
            DBConnection db=new DBConnection();
            db.dbconnection();
            String sql="insert into Export values(?,?,?,?,?,?,?,?,?)";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,((JTextField)dateExport.getDateEditor().getUiComponent()).getText());
            db.pst.setString(2,txtEProductId.getText());
            db.pst.setString(3,fish);
            db.pst.setFloat(4, price);
            db.pst.setFloat(5,quantity);
            db.pst.setFloat(6,tax_in_tk);
            db.pst.setFloat(7,sub_total_price);
            db.pst.setString(8,cmbCompanyIDExportF.getSelectedItem().toString());
            db.pst.setString(9,txtEManagerId.getText());
            
              String sql1="select EP_id from Export";
                db.rs=db.st.executeQuery(sql1);
                while(db.rs.next()){
                String id=db.rs.getString("EP_id");
                if(id.equals(txtEProductId.getText()))
                {
                    JOptionPane.showMessageDialog(null,"Product ID is already exists!!!");
                    txtEProductId.setText("P");
                    break;
               }
             }
                
            if(txtEProductId.getText().isEmpty() || txtEPrice.getText().isEmpty() || txtEQuantity.getText().isEmpty() || txtETax.getText().isEmpty() || txtEManagerId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill up all information");
            }
           else{
                String sql2="select C_id from Company";
                db.rs=db.st.executeQuery(sql2);
                
                String sql3="select M_id from Manager";
                db.rs=db.st.executeQuery(sql3);
                while(db.rs.next()){
                  m_id=db.rs.getString("M_id");
            
                  if(m_id.equals(txtEManagerId.getText()))
                  {
                    man_id=m_id;
                    break;
                  }
                }
                if(man_id.equals(txtEManagerId.getText())){
                      db.pst.executeUpdate();
                      close();
                      JOptionPane.showMessageDialog(null,"Successful inserted");
                      db.con.close();
                    }
                   else
                   {
                       txtEManagerId.setText("M");
                       JOptionPane.showMessageDialog(null,"Company or Manager ID is incorrect.");
                   }
            }       
       }  
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }  
    }//GEN-LAST:event_btnInsertCompanyInfoActionPerformed

    private void btnIUpdateCompanyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIUpdateCompanyInfoActionPerformed
        DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            float price=(float) 0.0;
           float quantity=(float) 0.0;
           float tax=(float) 0.0;
            try{
                 price=Float.parseFloat(txtEPrice.getText());
            }
            catch(NumberFormatException nfe){
                txtEPrice.setText("");
                JOptionPane.showMessageDialog(null,"Insert numeric Value of Price..");
            }
            try{
                quantity=Float.parseFloat(txtEQuantity.getText());
            }
            catch(NumberFormatException nfe){
                txtEQuantity.setText("");
                JOptionPane.showMessageDialog(null,"Insert numeric Value of Quantity..");
            }
            try{
                tax=Float.parseFloat(txtETax.getText());
            }
            catch(NumberFormatException nfe){
                txtETax.setText("");
                JOptionPane.showMessageDialog(null,"Insert numeric Value of Tax..");
            }
            float tax_in_tk=(float) ((price*tax)/100.0);
            float sub_total_price=(tax_in_tk*quantity)+(price*quantity);
            String fish=(String)cmboxExportForm.getSelectedItem();
            
            String sql="update Export set Date=?,P_name=?,Price=?,Quantity_KG=?,Tax=?,Sub_Total=? where EP_id=?";
            
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,((JTextField)dateExport.getDateEditor().getUiComponent()).getText());
            db.pst.setString(2,fish);
            db.pst.setFloat(3, price);
            db.pst.setFloat(4,quantity);
            db.pst.setFloat(5,tax);
            db.pst.setFloat(6,sub_total_price);
            db.pst.setString(7,txtEProductId.getText());
            if(txtEProductId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Insert only Company ID Number.");
            }
            else{
                db.pst.executeUpdate();
                close();
                JOptionPane.showMessageDialog(null,"Successfully Updated");
            }
            db.con.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
            close();
        }
    }//GEN-LAST:event_btnIUpdateCompanyInfoActionPerformed

    private void btnIDeleteCompanyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDeleteCompanyInfoActionPerformed
        DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            String sql="Delete from Export where EP_id=?";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,txtEProductId.getText());
            if(txtEProductId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Insert only Company ID Number.");
            }
            else{
                db.pst.executeUpdate();
                close();
                JOptionPane.showMessageDialog(null,"Successfully Deleted.");
            }
            db.con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please Insert only Company ID Number.");
            close();
        }
    }//GEN-LAST:event_btnIDeleteCompanyInfoActionPerformed

     private void close(){
        txtEManagerId.setText("M");
        txtEPrice.setText("");
        txtEProductId.setText("P");
        txtEQuantity.setText("");
        txtETax.setText("");
        dateExport.setDate(null);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackExportForm;
    private javax.swing.JButton btnIDeleteCompanyInfo;
    private javax.swing.JButton btnIUpdateCompanyInfo;
    private javax.swing.JButton btnInsertCompanyInfo;
    private static javax.swing.JComboBox<String> cmbCompanyIDExportF;
    private javax.swing.JComboBox<String> cmboxExportForm;
    private com.toedter.calendar.JDateChooser dateExport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblECompanyId;
    private javax.swing.JLabel lblEDate;
    private javax.swing.JLabel lblEManagerId;
    private javax.swing.JLabel lblEPrice;
    private javax.swing.JLabel lblEProductId;
    private javax.swing.JLabel lblEProductName;
    private javax.swing.JLabel lblEQuantity;
    private javax.swing.JLabel lblETax;
    private javax.swing.JTable tbtCompanyExport;
    private javax.swing.JTextField txtEManagerId;
    private javax.swing.JTextField txtEPrice;
    private javax.swing.JTextField txtEProductId;
    private javax.swing.JTextField txtEQuantity;
    private javax.swing.JTextField txtETax;
    // End of variables declaration//GEN-END:variables
}
