/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishexportandimportinformationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ManagerInfo extends javax.swing.JFrame {

    /**
     * Creates new form ManagerInfo
     */
    public ManagerInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblManagerID = new javax.swing.JLabel();
        lblManagerName = new javax.swing.JLabel();
        lblManagerMobile = new javax.swing.JLabel();
        lblManagerUsername = new javax.swing.JLabel();
        lblManagerPassword = new javax.swing.JLabel();
        txtManagerInfoId = new javax.swing.JTextField();
        txtManagerInfoName = new javax.swing.JTextField();
        txtManagerInfoMobile = new javax.swing.JTextField();
        txtManagerInfoUsername = new javax.swing.JTextField();
        txtManagerInfoPassword = new javax.swing.JTextField();
        btnBackManagerInfo = new javax.swing.JButton();
        btnManagerInfoUpdate = new javax.swing.JButton();
        btnManagerInfoDelete = new javax.swing.JButton();
        btnManagerInfoInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manaer Information");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lblManagerID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblManagerID.setForeground(new java.awt.Color(0, 0, 51));
        lblManagerID.setText("ID:");

        lblManagerName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblManagerName.setForeground(new java.awt.Color(0, 0, 51));
        lblManagerName.setText("Name:");

        lblManagerMobile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblManagerMobile.setForeground(new java.awt.Color(0, 0, 51));
        lblManagerMobile.setText("Mobile:");

        lblManagerUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblManagerUsername.setForeground(new java.awt.Color(0, 0, 51));
        lblManagerUsername.setText("Username:");

        lblManagerPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblManagerPassword.setForeground(new java.awt.Color(0, 0, 51));
        lblManagerPassword.setText("Password:");

        btnBackManagerInfo.setBackground(new java.awt.Color(0, 102, 153));
        btnBackManagerInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBackManagerInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnBackManagerInfo.setText("Back");
        btnBackManagerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackManagerInfoActionPerformed(evt);
            }
        });

        btnManagerInfoUpdate.setBackground(new java.awt.Color(0, 0, 51));
        btnManagerInfoUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManagerInfoUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerInfoUpdate.setText("Update");
        btnManagerInfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerInfoUpdateActionPerformed(evt);
            }
        });

        btnManagerInfoDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnManagerInfoDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManagerInfoDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerInfoDelete.setText("Delete");
        btnManagerInfoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerInfoDeleteActionPerformed(evt);
            }
        });

        btnManagerInfoInsert.setBackground(new java.awt.Color(0, 102, 0));
        btnManagerInfoInsert.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManagerInfoInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerInfoInsert.setText("Insert");
        btnManagerInfoInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerInfoInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblManagerUsername)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblManagerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManagerInfoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManagerInfoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtManagerInfoName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(txtManagerInfoMobile, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(187, 187, 187))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtManagerInfoId)
                                .addGap(186, 186, 186)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManagerInfoUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManagerInfoDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManagerInfoInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackManagerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManagerInfoInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManagerInfoName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagerInfoUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManagerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManagerInfoMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnManagerInfoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerInfoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerInfoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnBackManagerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackManagerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackManagerInfoActionPerformed
        setVisible(false);
        new AdminAfterLogin().setVisible(true);
    }//GEN-LAST:event_btnBackManagerInfoActionPerformed

    private void btnManagerInfoInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerInfoInsertActionPerformed
        DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            String sql="insert into Manager values(?,?,?,?,?)";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,txtManagerInfoId.getText());
            db.pst.setString(2,txtManagerInfoName.getText());
            db.pst.setString(3,txtManagerInfoMobile.getText());
            db.pst.setString(4,txtManagerInfoUsername.getText());
            db.pst.setString(5,txtManagerInfoPassword.getText());
            
                String query="select * from Manager";
                db.rs=db.st.executeQuery(query);
                while(db.rs.next()){
                String id=db.rs.getString("M_id");
                if(id.equals(txtManagerInfoId.getText()))
                {
                    JOptionPane.showMessageDialog(null,"ID is already exists!!!");
                    txtManagerInfoId.setText(" ");
                    break;
                }
            }
            
            if(txtManagerInfoId.getText().isEmpty() || txtManagerInfoMobile.getText().isEmpty() || txtManagerInfoName.getText().isEmpty() || txtManagerInfoPassword.getText().isEmpty() || txtManagerInfoUsername.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please fill up all information");
            }
            else{
                db.pst.executeUpdate();
                db.con.close();
                close();
                JOptionPane.showMessageDialog(null,"Successful inserted");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnManagerInfoInsertActionPerformed

    private void btnManagerInfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerInfoUpdateActionPerformed
        DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            String sql="update Manager set M_name=?,Mobile=?,Username=?,Password=? where M_id=?";
            db.pst=db.con.prepareStatement(sql);
            
            db.pst.setString(1,txtManagerInfoName.getText());
            db.pst.setString(2,txtManagerInfoMobile.getText());
            db.pst.setString(3,txtManagerInfoUsername.getText());
            db.pst.setString(4,txtManagerInfoPassword.getText());
            db.pst.setString(5,txtManagerInfoId.getText());
            if(txtManagerInfoId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Insert only Manager ID Number.");
            }
            else{
                db.pst.executeUpdate();
                db.con.close();
                close();
                JOptionPane.showMessageDialog(null,"Successfully Updated");
            }
            db.con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please Fill up The Boxes.");
            close();
        }
    }//GEN-LAST:event_btnManagerInfoUpdateActionPerformed

    private void btnManagerInfoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerInfoDeleteActionPerformed
        DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            String sql="Delete from Manager where M_id=?";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,txtManagerInfoId.getText());
            if(txtManagerInfoId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Insert only Manager ID Number.");
            }
            else{
                db.pst.executeUpdate();
                db.con.close();
                close();
                JOptionPane.showMessageDialog(null,"Successfully Deleted.");
            }
            db.con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please Insert only Manager ID Number.");
            close();
        }
    }//GEN-LAST:event_btnManagerInfoDeleteActionPerformed

    private void close(){
        txtManagerInfoId.setText(" ");
        txtManagerInfoMobile.setText(" ");
        txtManagerInfoName.setText(" ");
        txtManagerInfoUsername.setText(" ");
        txtManagerInfoPassword.setText(" ");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackManagerInfo;
    private javax.swing.JButton btnManagerInfoDelete;
    private javax.swing.JButton btnManagerInfoInsert;
    private javax.swing.JButton btnManagerInfoUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblManagerID;
    private javax.swing.JLabel lblManagerMobile;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblManagerPassword;
    private javax.swing.JLabel lblManagerUsername;
    private javax.swing.JTextField txtManagerInfoId;
    private javax.swing.JTextField txtManagerInfoMobile;
    private javax.swing.JTextField txtManagerInfoName;
    private javax.swing.JTextField txtManagerInfoPassword;
    private javax.swing.JTextField txtManagerInfoUsername;
    // End of variables declaration//GEN-END:variables
}
