/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishexportandimportinformationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SupplierInformation extends javax.swing.JFrame {

    private String gender=null;
    /**
     * Creates new form SupplierInformation
     */
    public SupplierInformation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSupplierId = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        lblSupplierMobile = new javax.swing.JLabel();
        lblSupplierAge = new javax.swing.JLabel();
        lblSupplieraddress = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        txtSupplierId = new javax.swing.JTextField();
        txtSupplierMobile = new javax.swing.JTextField();
        cmboxSupplierAge = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rdoSupplierGenderMale = new javax.swing.JRadioButton();
        rdoSupplierGenderFemale = new javax.swing.JRadioButton();
        btnSupplierInformation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaSupplierAddress = new javax.swing.JTextArea();
        lblSupplierManagerId = new javax.swing.JLabel();
        txtSupplierManagerId = new javax.swing.JTextField();
        btnInsertSupplierInfo = new javax.swing.JButton();
        btnUpdateSupplierInfo = new javax.swing.JButton();
        btnIDeleteSupplierInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supplier Information");
        setMinimumSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 450));
        jPanel1.setName(""); // NOI18N

        lblSupplierId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplierId.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierId.setText("ID:");

        lblSupplierName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplierName.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierName.setText("Name:");

        lblSupplierMobile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplierMobile.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierMobile.setText("Mobile:");

        lblSupplierAge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplierAge.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierAge.setText("Age:");

        lblSupplieraddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplieraddress.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplieraddress.setText("Address:");

        cmboxSupplierAge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmboxSupplierAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gender:");

        buttonGroup1.add(rdoSupplierGenderMale);
        rdoSupplierGenderMale.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rdoSupplierGenderMale.setForeground(new java.awt.Color(255, 255, 255));
        rdoSupplierGenderMale.setText("Male");
        rdoSupplierGenderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSupplierGenderMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoSupplierGenderFemale);
        rdoSupplierGenderFemale.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rdoSupplierGenderFemale.setForeground(new java.awt.Color(255, 255, 255));
        rdoSupplierGenderFemale.setText("Female");
        rdoSupplierGenderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSupplierGenderFemaleActionPerformed(evt);
            }
        });

        btnSupplierInformation.setBackground(new java.awt.Color(204, 204, 204));
        btnSupplierInformation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSupplierInformation.setForeground(new java.awt.Color(0, 0, 0));
        btnSupplierInformation.setText("Back");
        btnSupplierInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierInformationActionPerformed(evt);
            }
        });

        txtareaSupplierAddress.setColumns(20);
        txtareaSupplierAddress.setRows(5);
        jScrollPane1.setViewportView(txtareaSupplierAddress);

        lblSupplierManagerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplierManagerId.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierManagerId.setText("Manager ID:");

        btnInsertSupplierInfo.setBackground(new java.awt.Color(0, 102, 0));
        btnInsertSupplierInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInsertSupplierInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertSupplierInfo.setText("Insert");
        btnInsertSupplierInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertSupplierInfoActionPerformed(evt);
            }
        });

        btnUpdateSupplierInfo.setBackground(new java.awt.Color(0, 0, 51));
        btnUpdateSupplierInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdateSupplierInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateSupplierInfo.setText("Update");
        btnUpdateSupplierInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupplierInfoActionPerformed(evt);
            }
        });

        btnIDeleteSupplierInfo.setBackground(new java.awt.Color(153, 0, 0));
        btnIDeleteSupplierInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnIDeleteSupplierInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnIDeleteSupplierInfo.setText("Delete");
        btnIDeleteSupplierInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDeleteSupplierInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupplierInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSupplierMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSupplierId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSupplierAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSupplieraddress, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(lblSupplierName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSupplierMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtSupplierId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(cmboxSupplierAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rdoSupplierGenderMale, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdoSupplierGenderFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblSupplierManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSupplierManagerId, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdateSupplierInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(btnInsertSupplierInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIDeleteSupplierInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSupplierManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSupplierManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupplierAge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmboxSupplierAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoSupplierGenderMale, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoSupplierGenderFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplieraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnInsertSupplierInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateSupplierInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIDeleteSupplierInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(btnSupplierInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplierInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierInformationActionPerformed
        setVisible(false);
        new AfterLogin().setVisible(true);
    }//GEN-LAST:event_btnSupplierInformationActionPerformed

    private void btnInsertSupplierInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertSupplierInfoActionPerformed
       DBConnection db=new DBConnection();
       db.dbconnection();
       try{
            String age=(String)cmboxSupplierAge.getSelectedItem();
            
            String sql="insert into Supplier values(?,?,?,?,?,?,?)";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,txtSupplierId.getText());
            db.pst.setString(2,txtSupplierName.getText());
            db.pst.setString(3,age);
            db.pst.setString(4,gender);
            db.pst.setString(5,txtSupplierMobile.getText());
            db.pst.setString(6,txtareaSupplierAddress.getText());
            db.pst.setString(7,txtSupplierManagerId.getText());
            
                String query="select * from Supplier";
                db.rs=db.st.executeQuery(query);
                while(db.rs.next()){
                String id=db.rs.getString("S_id");
                if(id.equals(txtSupplierId.getText()))
                {
                    JOptionPane.showMessageDialog(null,"ID is already exists!!!");
                    txtSupplierId.setText(" ");
                    break;
                }
            }
            
            if(txtSupplierId.getText().isEmpty() || txtSupplierName.getText().isEmpty() || txtSupplierMobile.getText().isEmpty()  || txtSupplierManagerId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please fill up all information");
            }
            else{
                db.pst.executeUpdate();
                close();
                JOptionPane.showMessageDialog(null,"Successful inserted");
                db.con.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }                    
    }//GEN-LAST:event_btnInsertSupplierInfoActionPerformed

    private void rdoSupplierGenderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSupplierGenderMaleActionPerformed
        gender="Male";
    }//GEN-LAST:event_rdoSupplierGenderMaleActionPerformed

    private void rdoSupplierGenderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSupplierGenderFemaleActionPerformed
         gender="Female";
    }//GEN-LAST:event_rdoSupplierGenderFemaleActionPerformed

    private void btnUpdateSupplierInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplierInfoActionPerformed
       DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            String age=(String)cmboxSupplierAge.getSelectedItem();
            String sql="update Supplier set S_name=?,Age=?,gender=?,S_mobile=?,S_address=? where S_id=?";
            db.pst=db.con.prepareStatement(sql);
            
            db.pst.setString(1,txtSupplierName.getText());
            db.pst.setString(2,age);
            db.pst.setString(2,gender);
            db.pst.setString(3,txtSupplierMobile.getText());
            db.pst.setString(4,txtareaSupplierAddress.getText());
            db.pst.setString(5,txtSupplierId.getText());
            if(txtSupplierId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Insert only Supplier ID Number.");
            }
            else{
                db.pst.executeUpdate();
                close();
                JOptionPane.showMessageDialog(null,"Successfully Updated");
            }
            db.con.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
            close();
        }
    }//GEN-LAST:event_btnUpdateSupplierInfoActionPerformed

    private void btnIDeleteSupplierInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDeleteSupplierInfoActionPerformed
        DBConnection db=new DBConnection();
        db.dbconnection();
        try{
            String sql="Delete from Supplier where S_id=?";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,txtSupplierId.getText());
            if(txtSupplierId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Insert only Supplier ID Number.");
            }
            else{
                db.pst.executeUpdate();
                close();
                JOptionPane.showMessageDialog(null,"Successfully Deleted.");
            }
            db.con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please Insert only Company ID Number.");
            close();
        }
    }//GEN-LAST:event_btnIDeleteSupplierInfoActionPerformed

    private void close(){
        txtSupplierId.setText(" ");
        txtSupplierName.setText(" ");
        txtSupplierMobile.setText(" ");
        txtareaSupplierAddress.setText(" ");
        txtSupplierManagerId.setText(" ");
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIDeleteSupplierInfo;
    private javax.swing.JButton btnInsertSupplierInfo;
    private javax.swing.JButton btnSupplierInformation;
    private javax.swing.JButton btnUpdateSupplierInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmboxSupplierAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSupplierAge;
    private javax.swing.JLabel lblSupplierId;
    private javax.swing.JLabel lblSupplierManagerId;
    private javax.swing.JLabel lblSupplierMobile;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblSupplieraddress;
    private javax.swing.JRadioButton rdoSupplierGenderFemale;
    private javax.swing.JRadioButton rdoSupplierGenderMale;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierManagerId;
    private javax.swing.JTextField txtSupplierMobile;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextArea txtareaSupplierAddress;
    // End of variables declaration//GEN-END:variables
}
