/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishexportandimportinformationsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewExportedProduct extends javax.swing.JFrame {

    /**
     * Creates new form ViewExportedProduct
     */
    public ViewExportedProduct() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblViewEPC_Id = new javax.swing.JLabel();
        txtViewEPC_Id = new javax.swing.JTextField();
        btnOkViewEP = new javax.swing.JButton();
        lblViewEPC_Name = new javax.swing.JLabel();
        txtViewEPC_Name = new javax.swing.JTextField();
        lblViewEPC_mobile = new javax.swing.JLabel();
        txtViewEPC_mobile = new javax.swing.JTextField();
        btnBackExportedproduct = new javax.swing.JButton();
        btnClearExportProduct = new javax.swing.JButton();
        lblViewEPC_country = new javax.swing.JLabel();
        txtViewEPC_country = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExportedProduct = new javax.swing.JTable();
        lblTaxEPView = new javax.swing.JLabel();
        txtViewEPC_Tax = new javax.swing.JTextField();
        lblTotalEPView = new javax.swing.JLabel();
        txtViewEPC_Total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));

        lblViewEPC_Id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblViewEPC_Id.setForeground(new java.awt.Color(255, 255, 255));
        lblViewEPC_Id.setText("Company Id:");

        btnOkViewEP.setBackground(new java.awt.Color(102, 102, 255));
        btnOkViewEP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnOkViewEP.setForeground(new java.awt.Color(255, 255, 255));
        btnOkViewEP.setText("Ok");
        btnOkViewEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkViewEPActionPerformed(evt);
            }
        });

        lblViewEPC_Name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblViewEPC_Name.setForeground(new java.awt.Color(255, 255, 255));
        lblViewEPC_Name.setText("Company Name:");

        lblViewEPC_mobile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblViewEPC_mobile.setForeground(new java.awt.Color(255, 255, 255));
        lblViewEPC_mobile.setText("Contact Number:");

        btnBackExportedproduct.setBackground(new java.awt.Color(153, 153, 255));
        btnBackExportedproduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBackExportedproduct.setForeground(new java.awt.Color(0, 0, 0));
        btnBackExportedproduct.setText("Back");
        btnBackExportedproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackExportedproductActionPerformed(evt);
            }
        });

        btnClearExportProduct.setBackground(new java.awt.Color(153, 153, 255));
        btnClearExportProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClearExportProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnClearExportProduct.setText("Clear");
        btnClearExportProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearExportProductActionPerformed(evt);
            }
        });

        lblViewEPC_country.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblViewEPC_country.setForeground(new java.awt.Color(255, 255, 255));
        lblViewEPC_country.setText("Country:");

        tblExportedProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manager ID", "Date", "Product  ID", "Product Name", "Price", "Quantity(KG)", "Tax", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(tblExportedProduct);

        lblTaxEPView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTaxEPView.setForeground(new java.awt.Color(255, 255, 255));
        lblTaxEPView.setText("Tax:");

        lblTotalEPView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotalEPView.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalEPView.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewEPC_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEPC_country, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaxEPView, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtViewEPC_country)
                    .addComponent(txtViewEPC_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtViewEPC_Tax))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewEPC_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblViewEPC_mobile))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalEPView, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtViewEPC_Name)
                    .addComponent(txtViewEPC_mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtViewEPC_Total))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackExportedproduct, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnClearExportProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOkViewEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblViewEPC_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewEPC_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewEPC_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewEPC_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackExportedproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtViewEPC_country, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewEPC_country, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtViewEPC_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewEPC_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClearExportProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewEPC_Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTaxEPView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTotalEPView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtViewEPC_Total)
                    .addComponent(btnOkViewEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkViewEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkViewEPActionPerformed
        try{
            float tax=0;
            float total=0;
            DBConnection db=new DBConnection();
            db.dbconnection();
            String sql="select Company.C_name,Company.C_contact_no,Company.C_country,Export.M_id,Export.Date,EP_id,Export.P_name,Export.Price,Export.Quantity_KG,Export.Tax,Export.Sub_Total from Export inner join Company on Export.C_id=Company.C_id where Export.C_id=?";
            db.pst=db.con.prepareStatement(sql);
            db.pst.setString(1,txtViewEPC_Id.getText());
            db.rs=db.pst.executeQuery();
            DefaultTableModel row=(DefaultTableModel) tblExportedProduct.getModel();
            while(db.rs.next()){
            txtViewEPC_country.setText(db.rs.getString("C_country"));
            txtViewEPC_Name.setText(db.rs.getString("C_name"));
            txtViewEPC_mobile.setText(db.rs.getString("C_contact_no"));
            tax+=db.rs.getFloat("Tax");
            total+=db.rs.getFloat("Sub_Total");
                row.addRow(new Object[]{
                    db.rs.getString("M_id"),db.rs.getString("Date"),db.rs.getString("EP_id"),db.rs.getString("P_name"),db.rs.getString("Price"),db.rs.getString("Quantity_KG"),db.rs.getString("Tax"),db.rs.getString("Sub_Total")
                } );
            }
            txtViewEPC_Tax.setText(String.valueOf(tax));
            txtViewEPC_Total.setText(String.valueOf(total));
            db.con.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnOkViewEPActionPerformed

    private void btnBackExportedproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackExportedproductActionPerformed
        setVisible(false);
        new ViewDataAdmin().setVisible(true);
    }//GEN-LAST:event_btnBackExportedproductActionPerformed

    private void btnClearExportProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearExportProductActionPerformed
       txtViewEPC_country.setText("");
       txtViewEPC_Name.setText("");
       txtViewEPC_mobile.setText("");
       txtViewEPC_Id.setText("C");
       setVisible(false);
       new ViewExportedProduct().setVisible(true);
    }//GEN-LAST:event_btnClearExportProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExportedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExportedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExportedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExportedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExportedProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackExportedproduct;
    private javax.swing.JButton btnClearExportProduct;
    private javax.swing.JButton btnOkViewEP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTaxEPView;
    private javax.swing.JLabel lblTotalEPView;
    private javax.swing.JLabel lblViewEPC_Id;
    private javax.swing.JLabel lblViewEPC_Name;
    private javax.swing.JLabel lblViewEPC_country;
    private javax.swing.JLabel lblViewEPC_mobile;
    private javax.swing.JTable tblExportedProduct;
    private javax.swing.JTextField txtViewEPC_Id;
    private javax.swing.JTextField txtViewEPC_Name;
    private javax.swing.JTextField txtViewEPC_Tax;
    private javax.swing.JTextField txtViewEPC_Total;
    private javax.swing.JTextField txtViewEPC_country;
    private javax.swing.JTextField txtViewEPC_mobile;
    // End of variables declaration//GEN-END:variables
}
